[versions]
kotlin = "2.0.21"
agp = "8.4.0"

compose-bom = "2024.10.01"
material = "1.12.0" # Google Material Components (важно!)

room = "2.6.1"
coroutines = "1.8.1"

webrtc = "1.0.+'"
libsodium = "5.1.0"
jna = "5.14.0"
java-websocket = "1.5.4"


[libraries]

# ANDROIDX
androidx-core-ktx = { module = "androidx.core:core-ktx", version = "1.13.1" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version = "2.8.6" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version = "1.9.3" }

# COMPOSE
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }

# ❗️ ОБЯЗАТЕЛЬНАЯ СТРОКА — ЧТОБЫ НЕ БЫЛО ОШИБОК С ТЕМОЙ
google-material = { module = "com.google.android.material:material", version.ref = "material" }

# ROOM
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }

# Криптография + WebRTC
libsodium-jni = { module = "com.goterl:lazysodium-android", version.ref = "libsodium" }
jna-aar = { module = "net.java.dev.jna:jna", version.ref = "jna" }
webrtc = { module = "org.webrtc:google-webrtc", version.ref = "webrtc" }

kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
java-websocket = { module = "org.java-websocket:Java-WebSocket", version.ref = "java-websocket" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version = "2.0.21-1.0.26" }
