[versions]
agp = "8.4.2"
kotlin = "2.0.20"
compose-bom = "2024.10.00"
room = "2.6.1"
ksp = "2.0.20-1.0.25"
webrtc = "1.3.10"
coroutines = "1.8.1"
lifecycle = "2.8.6"
activity-compose = "1.9.2"
java-websocket = "1.5.6"
libsodium = "2.0.2"
material-icons = "1.6.8"

[libraries]
androidx-core-ktx = "androidx.core:core-ktx:1.13.1"
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }

compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "material-icons" }

room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }

webrtc = { module = "io.getstream:stream-webrtc-android", version.ref = "webrtc" }

kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }

# New: For skeleton code
java-websocket = { module = "org.java-websocket:Java-WebSocket", version.ref = "java-websocket" }
libsodium-jni = { module = "com.muquit.libsodiumjna:libsodium-jni-aar", version.ref = "libsodium" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
