# gradle.properties (как в phase1 — включает APK)
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true

android.useAndroidX=true
android.enableJetifier=true

# ← КОПИЯ ИЗ PHASE1 — ВКЛЮЧАЕТ APK
android.bundle.enableUncompressedNativeLibs=false
android.defaults.buildfeatures.buildconfig=true
android.defaults.buildfeatures.aidl=true
android.defaults.buildfeatures.renderscript=true
android.defaults.buildfeatures.resvalues=true
android.defaults.buildfeatures.shaders=true
kotlin.code.style=official
