name: Build Kakdela

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # Устанавливаем Android SDK
      - name: Install Android SDK
        run: |
          sudo mkdir -p /usr/local/android-sdk
          sudo chown $USER:$USER /usr/local/android-sdk

          wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip
          unzip commandlinetools-linux-10406996_latest.zip
          rm commandlinetools-linux-10406996_latest.zip

          mkdir -p /usr/local/android-sdk/cmdline-tools
          mv cmdline-tools /usr/local/android-sdk/cmdline-tools/latest

          yes | /usr/local/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=/usr/local/android-sdk "platform-tools"
          yes | /usr/local/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=/usr/local/android-sdk "platforms;android-35"
          yes | /usr/local/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=/usr/local/android-sdk "build-tools;35.0.0"
          yes | /usr/local/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses

      # Доступ к SDK для gradle
      - name: Set ANDROID_HOME
        run: echo "ANDROID_HOME=/usr/local/android-sdk" >> $GITHUB_ENV

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # Сборка APK
      - name: Build Debug APK
        run: ./gradlew assembleDebug

      # Загружаем APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Kakdela-debug
          path: app/build/outputs/apk/debug/app-debug.apk
